// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmyoocrnphnnsuoqhktc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teW9vY3JucGhubnN1b3Foa3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTk1ODMsImV4cCI6MjA3MTc3NTU4M30.AeK7x9jNujec5IoUsni4tsZzV-wTbEre3neJNa_GisI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});